spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health_manager?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: Zj20190901

upload-path: C:/upload/

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com:
      example:
        demo:
          mapper: debug