upload-path: C:/upload/
#upload-path: /root/upload/


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.32.161:3306/health_manager?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: health_manager
    password: hust_sse_2018
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true


mybatis:
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    com:
      example:
        demo:
          mapper: debug